---
apiVersion: v1
kind: Secret
metadata:
  name: stanaka-dev-wheres-teddy-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/devhub-tanaka/stanaka-dev-wheres-teddy-gitops
